name: appdelicia_flutter
description: Migración AppDelicia a Flutter (scaffold funcional)
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cached_network_image: ^3.2.4 # opcional si algunas imágenes están remotas en un futuro

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
